theme: minima
title: Practica Pages
author: EdisonPadilla
email: edison.padilla@epn.edu.ec
description: > # this means to ignore newlines until "baseurl:"
  Mi primer super hiper mega genialmente genial sitio.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
